// taskwords are the texts of the task pages: the list, board and tree, a task's page, and the forms that create, edit,
// dispatch, move, review a plan and accept work.
import {register} from '../core/i18n.js';

register('tasks', {
  'tasks.title': ['任务', 'Tasks'], 'tasks.view': ['视图', 'View'], 'tasks.view.list': ['列表', 'List'], 'tasks.view.board': ['看板', 'Board'],
  'tasks.view.tree': ['树', 'Tree'], 'tasks.mine': ['我的', 'Mine'], 'tasks.all': ['全部', 'All'], 'tasks.anyProject': ['全部项目', 'Every project'],
  'tasks.filter': ['筛选', 'Filter'], 'tasks.search': ['搜索标题、编号或标签', 'Search titles, ids or tags'], 'tasks.new': ['新建', 'New'],
  'tasks.none': ['没有符合的任务', 'No task matches'], 'tasks.col.title': ['任务', 'Task'], 'tasks.col.why': ['处境', 'Where it stands'],
  'tasks.col.who': ['Agent @ 机器', 'Agent @ machine'], 'tasks.col.updated': ['更新', 'Updated'], 'tasks.col.project': ['项目', 'Project'],
  'col.waiting': ['等你', 'Waiting on you'], 'col.running': ['运行中', 'Running'], 'col.queued': ['排队', 'Queued'],
  'col.backlog': ['未开始', 'Not started'], 'col.ended': ['已结束', 'Ended'],
  'board.no.flow': ['走 workflow 的任务由它最后一个阶段完成，不能拖到「已结束」。', 'A workflow task is finished by its last stage, not by a drop.'],
  'board.no.open': ['它还有没结束的运行：先停下它。', 'A run of it is still open: stop that first.'],
  'board.no.rule': ['看板上只能标完成、先不开始、开始和重开。', 'The board only marks done, holds back, starts and reopens.'],
  'do.start': ['开始', 'Start'], 'do.stop': ['停止', 'Stop'], 'do.review': ['评审草稿', 'Review the plan'], 'do.gate': ['验收', 'Accept'],
  'do.ack': ['采用新版本', 'Take the new version'], 'do.keep': ['维持本轮范围', 'Keep this round'], 'do.keepGoing': ['继续做', 'Keep going'],
  'do.merge': ['重试合并', 'Merge again'], 'do.done': ['完成', 'Mark done'], 'do.sendBack': ['退回意见', 'Send it back'],
  'do.dispatch': ['派发', 'Dispatch'], 'do.plan': ['让 agent 拆解', 'Have an agent plan it'], 'do.backlog': ['先不开始', 'Not yet'],
  'do.edit': ['编辑', 'Edit'], 'do.move': ['调整位置', 'Move'], 'do.child': ['新建子任务', 'New subtask'], 'do.copy': ['照这个再建一个', 'Another like this'],
  'do.cancel': ['取消任务', 'Cancel the task'], 'do.reopen': ['重开', 'Reopen'], 'do.more': ['更多', 'More'],
  'toast.started': ['「%s」已开始', '%s started'], 'toast.stopping': ['正在停止「%s」的运行', 'Stopping the run of %s'],
  'toast.done': ['「%s」已完成', '%s is done'], 'toast.reopened': ['「%s」已重开', '%s is open again'],
  'toast.backlog': ['「%s」放进了未开始', '%s is held back'], 'toast.canceled': ['「%s」已取消', '%s is canceled'],
  'toast.moved': ['调整了「%s」的位置', '%s moved'], 'toast.created': ['新建了「%s」', '%s created'], 'toast.saved': ['「%s」已保存', '%s saved'],
  'toast.dispatched': ['「%s」已排队', '%s is queued'], 'toast.planning': ['正在让 agent 拆解「%s」', 'An agent plans %s'],
  'toast.applied': ['按草稿建出了 %d 个任务', '%d tasks made from the plan'], 'toast.discarded': ['草稿已丢弃', 'The plan is dropped'],
  'toast.draftSaved': ['草稿已保存', 'The plan is saved'], 'toast.passed': ['「%s」验收通过', '%s passed'],
  'toast.sentBack': ['「%s」已退回', '%s is sent back'], 'toast.acked': ['已采用 issue 的新版本', 'The issue\'s new version is taken'],
  'toast.kept': ['维持当前范围', 'The scope stays'], 'toast.merging': ['正在重新合并「%s」', 'Merging %s again'],
  'toast.replied': ['已发给 %s', 'Sent to %s'], 'toast.moved.board': ['「%s」→「%s」', '%s → %s'],
  'confirm.cancel': ['取消这个任务？', 'Cancel this task?'], 'confirm.cancelNote': ['「%s」和它下面没完成的子任务都会取消。', '%s and its unfinished subtasks are canceled.'],
  'confirm.keep': ['留着', 'Keep it'],
  'det.brief': ['任务书', 'Brief'], 'det.noBrief': ['还没有任务书', 'No brief yet'], 'det.accept': ['验收标准', 'Acceptance'],
  'det.parent': ['父任务', 'Parent'], 'det.after': ['先完成', 'Comes after'], 'det.kids': ['子任务', 'Subtasks'],
  'det.kidsN': ['%d / %d 完成', '%d of %d done'], 'det.runs': ['运行记录', 'Runs'], 'det.noRuns': ['还没有运行', 'No run yet'],
  'det.flow': ['Workflow · %s', 'Workflow · %s'], 'det.round': ['第 %d 轮', 'round %d'], 'det.gateHuman': ['人工验收', 'human gate'],
  'det.notes': ['工作记录', 'Workpad'], 'det.owner': ['负责人', 'Owner'], 'det.approver': ['验收人', 'Approver'], 'det.project': ['项目', 'Project'],
  'det.dir': ['目录', 'Directory'], 'det.runsOn': ['在哪跑', 'Runs on'], 'det.projectDefault': ['%s（项目默认）', '%s (project default)'],
  'det.spent': ['全部运行', 'All runs'], 'det.spentN': ['%d 次 · %s tok%s', '%d runs · %s tok%s'], 'det.branch': ['分支', 'Branch'],
  'det.loading': ['读取中…', 'Loading…'], 'det.gone': ['这个任务不在了，或者你看不到它。', 'This task is gone, or not yours to see.'],
  'det.sourceNew': ['issue 有了第 %d 版：', 'The issue has a version %d:'], 'det.sourceClosed': ['issue 已在外面关闭。', 'The issue was closed outside tend.'],
  'det.issue': ['来源 issue', 'Issue'], 'det.requirement': ['需求', 'Requirement'], 'det.draft': ['拆解草稿：%d 条', 'A plan of %d tasks'], 'det.stages': ['阶段', 'Stages'],
  'det.verdict': ['结论：%s', 'Verdict: %s'], 'det.took': ['用了 %s', 'took %s'],
  'form.new': ['新建任务', 'New task'], 'form.edit': ['编辑「%s」', 'Edit %s'], 'form.child': ['新建「%s」的子任务', 'A subtask of %s'],
  'form.copy': ['照「%s」再建一个', 'Another like %s'], 'form.title': ['标题', 'Title'], 'form.titleNeeded': ['写一个标题', 'Give it a title'],
  'form.brief': ['任务书', 'Brief'], 'form.briefNote': ['Markdown · ⌘Enter 提交 · Enter 换行', 'Markdown · ⌘Enter submits · Enter breaks the line'],
  'form.write': ['编辑', 'Write'], 'form.preview': ['预览', 'Preview'], 'form.project': ['项目', 'Project'], 'form.noProject': ['不属于项目', 'No project'],
  'form.dir': ['目录', 'Directory'], 'form.dirNote': ['所选机器上的路径', 'The path on the machine picked'], 'form.dirProject': ['项目目录', 'project'],
  'form.dirRecent': ['最近用过', 'recent'], 'form.dirChecking': ['正在检查…', 'Checking…'], 'form.dirOK': ['这台机器上有这个目录', 'The machine has this directory'],
  'form.dirMissing': ['这台机器上没有这个目录', 'The machine has no such directory'], 'form.dirOther': ['自己填', 'Type one'],
  'form.machine': ['机器', 'Machine'], 'form.agent': ['Agent', 'Agent'], 'form.default': ['项目默认（%s）', 'Project default (%s)'],
  'form.unset': ['不指定', 'None'], 'form.workflow': ['Workflow', 'Workflow'], 'form.workflowNone': ['不走 workflow', 'No workflow'],
  'form.parent': ['父任务', 'Parent'], 'form.top': ['顶层', 'None (top level)'], 'form.after': ['先完成这些任务', 'Comes after'],
  'form.accept': ['验收标准', 'Acceptance'], 'form.acceptNote': ['一行一条', 'One per line'], 'form.draftNote': ['草稿只存在这台设备上', 'The draft is kept on this device only'],
  'form.createStart': ['创建并开始', 'Create and start'], 'form.createBacklog': ['放进待办', 'Put in the backlog'], 'form.createPlan': ['先让 agent 拆解', 'Have an agent plan it first'],
  'form.save': ['保存', 'Save'], 'form.failed': ['没有办成：%s', 'That did not work: %s'],
  'm.inUse': ['%d/%d 在用', '%d/%d in use'], 'm.full': ['%d/%d 满', '%d/%d full'], 'm.offline': ['离线', 'offline'], 'a.only': ['只在 %s', 'only on %s'],
  'disp.title': ['派发「%s」', 'Dispatch %s'], 'disp.go': ['确认并排队', 'Confirm and queue'], 'disp.later': ['先不开始', 'Not yet'],
  'disp.checking': ['正在预览…', 'Previewing…'], 'disp.cli': ['%s %s', '%s %s'],
  'adv.open': ['已经有一个没结束的运行 %s：先让它结束。', 'Run %s is still open: let it end first.'],
  'adv.status': ['这个任务不是待办（%s），不能派发。', 'This task is not to do (%s): it cannot be dispatched.'],
  'adv.dir': ['任务没有目录：先编辑它。', 'The task has no directory: edit it first.'], 'adv.pick': ['选好机器和 agent。', 'Pick a machine and an agent.'],
  'adv.pinned': ['这个 agent 只在 %s 上跑。', 'This agent runs on %s only.'], 'adv.cli': ['这台机器上没有装 %s。', 'The machine has no %s.'],
  'adv.auth': ['%s 在这台机器上没登录。', '%s is not signed in there.'], 'adv.offline': ['%s 离线：它连上以后才开始。', '%s is offline: it starts once it answers.'],
  'adv.busy': ['机器忙（%s 在用）或同一目录有运行：排队等。', 'The machine is busy (%s in use) or its directory is: it queues.'],
  'pv.cli_missing': ['这台机器上没有这个 CLI', 'The CLI is not on the machine'], 'pv.auth_missing': ['CLI 没登录', 'The CLI is not signed in'],
  'pv.node_outdated': ['这台机器上的 tend 太旧', 'The machine\'s tend is too old'], 'pv.no_access': ['你或这个项目不能用这台机器', 'You or the project may not use the machine'],
  'pv.def_pending': ['定义里的 MCP 或 hook 用不上', 'The definition\'s MCP servers or hooks do not apply'], 'pv.offline': ['机器离线：连上后开始', 'Offline: it starts once the machine answers'],
  'pv.connecting': ['正在连接机器', 'The machine is connecting'], 'pv.slots': ['等空位', 'It waits for a slot'], 'pv.dir_busy': ['等同一目录的运行结束', 'It waits for the run in its directory'],
  'pv.auth_unknown': ['不知道 CLI 登没登录', 'Not known whether the CLI is signed in'], 'pv.unchecked': ['没查过这台机器的 CLI', 'The machine\'s CLI was not checked'],
  'pv.herdr': ['可能在 Herdr 的标签页里打开', 'It may open in a Herdr tab'], 'pv.background': ['在后台跑', 'It runs in the background'],
  'pv.continues': ['接着之前的会话', 'It continues an earlier session'],
  'plan.title': ['拆解草稿 · %s', 'The plan · %s'], 'plan.by': ['planner 运行 %s', 'planner run %s'], 'plan.questions': ['planner 的问题', 'The planner asks'],
  'plan.reply': ['补充意见，重新拆解', 'Add a note and plan again'], 'plan.replyNote': ['作为 %s 的回复：同一个会话里重出草稿', 'A reply to %s: the same session plans again'],
  'plan.send': ['发送', 'Send'], 'plan.add': ['加一条', 'Add a task'], 'plan.remove': ['删掉', 'Remove'], 'plan.editItem': ['编辑这一条', 'Edit this task'],
  'plan.key': ['标识', 'Key'], 'plan.partOf': ['属于', 'Part of'], 'plan.size': ['规模', 'Size'], 'plan.role': ['由哪类 agent 做', 'Done by'],
  'plan.machineHint': ['建议机器', 'Machine hint'], 'plan.save': ['保存草稿', 'Save the plan'], 'plan.apply': ['按草稿建任务', 'Make the tasks'],
  'plan.saveFirst': ['先保存改动，再建任务。', 'Save the changes before making the tasks.'], 'plan.discard': ['丢弃草稿', 'Drop the plan'],
  'plan.items': ['%d 条', '%d tasks'], 'plan.back': ['回到草稿', 'Back to the plan'],
  'plan.err.empty': ['草稿里没有任务', 'The plan has no tasks'], 'plan.err.many': ['最多 %s 条', 'At most %s tasks'],
  'plan.err.key': ['标识只能用小写字母、数字、- 和 _', 'A key is lowercase letters, digits, - and _'], 'plan.err.twice': ['标识重复了', 'The key is used twice'],
  'plan.err.title': ['要有标题（最多 1024 字节）', 'A title of 1 to 1024 bytes'], 'plan.err.size': ['规模是 S、M 或 L', 'Size is S, M or L'],
  'plan.err.parent': ['没有「%s」这一条', 'There is no %s'], 'plan.err.deep': ['草稿最多两层', 'A plan is two levels at most'],
  'plan.err.after': ['没有「%s」这一条', 'There is no %s'], 'plan.err.own': ['不能排在「%s」之后：它属于那一条或包含它', 'It cannot come after %s, which holds it or is part of it'],
  'plan.err.cycle': ['先后顺序绕成了一个圈', 'The order goes round in a circle'],
  'gate.title': ['验收「%s」', 'Accept %s'], 'gate.pass': ['通过', 'Pass'], 'gate.back': ['退回', 'Send back'],
  'gate.notes': ['退回意见', 'What to change'], 'gate.notesNote': ['会交给下一轮', 'The next round is told'], 'gate.needNotes': ['退回要写意见', 'Say what to change'],
  'gate.waits': ['等 %s 验收', 'Waits for %s to accept it'], 'gate.stage': ['%s 阶段 · 第 %d 轮', 'stage %s · round %d'],
  'gate.replyNote': ['作为 %s 的回复：同一个会话里接着改', 'A reply to %s: the same session goes on'],
  'move.title': ['调整「%s」的位置', 'Move %s'],
});
