// words are the pages' texts: sign-in, terminal authorization, invitation, the home, and why a task waits.
import {register} from '../core/i18n.js';

register('pages', {
  'auth.title': ['登录 tend', 'Sign in to tend'], 'auth.tagline': ['看住每一个 agent 的运行', 'Keep an eye on every agent run'],
  'auth.with': ['用 %s 登录', 'Sign in with %s'], 'auth.acceptWith': ['用 %s 接受邀请', 'Accept with %s'],
  'auth.orToken': ['或使用 token', 'Or use a token'], 'auth.token': ['Token', 'Token'], 'auth.tokenPlaceholder': ['tend_…', 'tend_…'],
  'auth.tokenNote': ['在 server 上运行 tend-server token add --client web 得到一个。', 'Run tend-server token add --client web on the server to get one.'],
  'auth.signIn': ['登录', 'Sign in'], 'auth.badToken': ['这个 token 不对或已失效。', 'That token is wrong or no longer valid.'],
  'auth.failed': ['登录没有成功：%s', 'The sign-in failed: %s'],
  'auth.inviteOnly': ['这是邀请制实例：只有管理员加过的人，或邮箱在准入规则里的人才能进来。', 'This is an invitation-only instance: only people an admin added, or whose email is admitted, may sign in.'],
  'auth.invitedBy': ['%s 邀请你以「%s」身份加入', '%s invited you to join as %s'],
  'auth.invitedTo': ['登录后加入项目「%s」，身份：%s', 'Signing in makes you a member of %s: %s'],
  'auth.device': ['在另一台设备上登录', 'Sign in from another device'],
  'auth.deviceTitle': ['在另一台设备上允许', 'Allow it on another device'],
  'auth.deviceHelp': ['在已经登录 tend 的电脑或手机上打开这个链接，核对码一致后允许；允许后这里自动登录。10 分钟内有效。', 'Open this link on a computer or phone already signed in to tend, check the code matches, and allow it; this device then signs in by itself. It works for 10 minutes.'],
  'auth.deviceShare': ['分享链接', 'Share the link'], 'auth.deviceCopy': ['复制链接', 'Copy the link'], 'auth.deviceCopied': ['已复制', 'Copied'],
  'auth.deviceWaiting': ['等待允许…', 'Waiting to be allowed…'], 'auth.deviceCancel': ['返回', 'Back'], 'auth.deviceAgain': ['重新来', 'Start again'],
  'auth.deviceDenied': ['那边拒绝了这次登录。', 'The sign-in was denied.'], 'auth.deviceExpired': ['这个码过期了，没有人允许。', 'The code expired before anyone allowed it.'],
  'auth.inviteExpires': ['链接 %s 失效', 'The link expires %s'], 'auth.inviteGone': ['这个邀请链接已经用过、作废或过期。', 'This invitation was used, revoked or has expired.'],
  'role.admin': ['管理员', 'admin'], 'role.member': ['成员', 'member'], 'role.owner': ['负责人', 'owner'],
  'role.participant': ['参与者', 'participant'], 'role.reader': ['只读', 'reader'],
  'signin.state': ['登录已过期或来自另一个浏览器，请重新开始。', 'The sign-in expired or began in another browser. Start again.'],
  'signin.provider': ['登录服务没有确认这次登录。', 'The sign-in service did not confirm this sign-in.'],
  'signin.linked': ['这个账号已经属于另一个用户。', 'This account already belongs to another user.'],
  'signin.internal': ['服务器出错，请稍后再试。', 'The server failed. Try again later.'],
  'denied.title': ['这个账号还不能进来', 'This account cannot come in yet'],
  'denied.notAdmitted': ['你用 %s 登录的是 %s，这个账号还没有被允许加入。', 'You signed in with %s as %s; that account is not admitted yet.'],
  'denied.disabled': ['这个用户已被停用。', 'This user is disabled.'],
  'denied.help': ['请管理员邀请你，或添加一条准入规则；也可以换一个账号登录。', 'Ask an admin to invite you or add an admission rule, or sign in with another account.'],
  'denied.switch': ['换一个账号', 'Use another account'], 'denied.copy': ['复制账号信息', 'Copy the account details'], 'denied.copied': ['已复制', 'Copied'],
  'device.title': ['允许终端登录？', 'Allow this sign-in?'], 'device.help': ['核对终端上显示的设备码，一致再允许。', 'Check the code shown in the terminal, then allow it.'],
  'device.titleSession': ['允许这台设备登录网页？', 'Allow this device to sign in?'],
  'device.helpSession': ['核对那台设备上显示的码，一致再允许。允许后它以你的身份登录 tend 网页，30 天有效；在「我」页的浏览器会话里让它退出，它的推送也一起停。', 'Check the code the device shows, then allow it. It signs in to tend as you for 30 days; signing it out from the me page\'s browser sessions stops its pushes too.'],
  'device.allowedSession': ['已允许，那台设备会自动登录。', 'Allowed. The device signs in by itself.'],
  'device.elsewhere': ['这个请求不是从你现在用的网络发来的（来源地址不同）。如果不是你自己的设备、或有人把链接发给了你，请拒绝：允许后对方就以你的身份登录。', 'This request did not come from the network you are on (another source address). If it is not your own device, or someone sent you this link, deny it: allowing it signs them in as you.'],
  'device.confirm': ['输入那台设备上显示的码的后四位', 'Type the last four characters of the code that device shows'],
  'device.confirmWrong': ['和那台设备上的码对不上', 'That does not match the code on the device'],
  'device.name': ['设备', 'Device'], 'device.ip': ['来源地址', 'Source address'], 'device.at': ['请求于', 'Requested'],
  'device.allow': ['允许', 'Allow'], 'device.deny': ['拒绝', 'Deny'], 'device.allowed': ['已允许，回到终端继续。', 'Allowed. Go back to the terminal.'],
  'device.denied': ['已拒绝。', 'Denied.'], 'device.gone': ['这个设备码已经用过或已过期。', 'This device code was already used, or has expired.'],
  'device.failed': ['没有办成：%s', 'That did not work: %s'], 'device.back': ['回到 tend', 'Back to tend'], 'device.loading': ['正在读取…', 'Loading…'],
  'app.logout': ['退出登录', 'Sign out'], 'app.theme': ['主题：%s', 'Theme: %s'], 'app.lang': ['English', '中文'],
  'theme.system': ['跟随系统', 'System'], 'theme.light': ['浅色', 'Light'], 'theme.dark': ['深色', 'Dark'],
  'density.default': ['标准', 'Standard'], 'density.compact': ['紧凑', 'Compact'], 'density.comfortable': ['宽松', 'Comfortable'],
  'app.density': ['密度：%s', 'Density: %s'],
  'app.failed': ['没有办成：%s', 'That did not work: %s'], 'app.unsure': ['不知道成没成（%s）', 'Not known whether it went through (%s)'],
  'app.retry': ['重试', 'Retry'],
  'api.exists': ['这个名字已经有了', 'That name is taken'], 'api.name': ['名字不合法', 'That name is not valid'],
  'api.csrf': ['请求被拒绝，请刷新页面', 'The request was refused: reload the page'], 'api.unauthorized': ['你没有这个权限', 'You may not do that'],
  'api.not_found': ['没有这一项，或者你看不到它', 'No such thing, or it is out of your sight'], 'api.self': ['不能改你自己', 'You cannot change yourself'],
  'api.no_webhook': ['还没有保存 webhook', 'No webhook is saved'],
  'api.last': ['这是你唯一的登录方式，不能解除', 'It is your only way to sign in, so it stays'],
  'api.bad_request': ['填的内容不对', 'Something filled in is not right'], 'api.project': ['没有这个项目', 'No such project'],
  'api.push_key': ['这台 server 没有推送密钥，推送用不了', 'This server has no push key, so pushes cannot be used'],
  'api.too_many_devices': ['你已经有 10 台收推送的设备了，先去掉一台', 'You already get pushes on 10 devices: remove one first'],
  'api.push_service': ['这个浏览器的推送服务不在 server 允许的范围里', 'This browser\'s push service is not one the server allows'],
  'api.offline': ['连不上服务器', 'The server cannot be reached'], 'api.internal': ['服务器出错了', 'The server failed'],
  'api.tracker_auth': ['token 被拒，或者权限不够', 'The token was refused or lacks access'], 'api.tracker_repo': ['找不到这个仓库', 'That repository was not found'],
  'api.tracker_unreachable': ['连不上工单系统', 'The tracker cannot be reached'], 'api.no_sync': ['这台 server 没有开工单同步', 'This server does not sync trackers'],
  'home.title': ['首页', 'Home'], 'home.waiting': ['等你', 'Waiting on you'], 'home.longest': ['最久一条等了 %s', 'The oldest has waited %s'],
  'home.none': ['没有等你处理的事', 'Nothing waits on you'],
  'home.g.answer': ['要回答', 'To answer'], 'home.g.accept': ['待验收', 'To accept'], 'home.g.error': ['出错', 'Failed'], 'home.g.other': ['其他', 'Other'],
  'home.going': ['在跑 / 排队', 'Running / queued'], 'home.peak': ['今天最多同时 %d 个', 'At most %d at once today'],
  'home.room': ['用了 %d 个位置，共 %d 个', '%d of %d {slot|slots} in use'],
  'home.ended': ['今天结束', 'Ended today'], 'home.mean': ['平均 %s', 'Mean %s'],
  'home.spent': ['今天花费', 'Spent today'], 'home.spentNote': ['%s tok · 7 天 %s', '%s tok · 7 days %s'],
  'home.all': ['全部', 'All'], 'home.asOwner': ['我负责', 'Mine'], 'home.asApprover': ['我验收', 'To accept'],
  'home.asDispatcher': ['我派发的', 'I dispatched'], 'home.hint': ['同类里等得久的在前 · 点开作答', 'Oldest first by kind · open one to answer'],
  'home.as.owner': ['你负责', 'yours'], 'home.as.approver': ['你验收', 'you accept'], 'home.as.dispatcher': ['你派发的', 'you dispatched'],
  'home.as.admin': ['管理员', 'as admin'],
  'home.running': ['在跑 %d · 排队 %d', '%d running · %d queued'], 'home.allRuns': ['全部运行', 'All runs'],
  'home.nothingRuns': ['现在没有在跑的运行', 'Nothing runs now'],
  'home.sessions': ['会话', 'Sessions'], 'home.sessShared': ['%s 共享', 'shared by %s'],
  'home.recent': ['最近结束', 'Ended lately'], 'home.today': ['今天', 'today'], 'home.noRecent': ['今天还没有运行结束', 'No run has ended today'],
  'home.lanes': ['今天的运行', "Today's runs"], 'home.lanesNote': ['按机器 · %s 到现在', 'By machine · %s to now'],
  'home.inUse': ['%d / %d 在用', '%d / %d in use'], 'home.full': ['%d / %d 满', '%d / %d full'], 'home.offline': ['离线', 'offline'],
  'home.week': ['近 7 天用量', 'The last 7 days'], 'home.weekNote': ['%s tok · claude 估算 %s', '%s tok · claude estimates %s'],
  'home.results': ['近 7 天运行结果', 'Runs of the last 7 days'], 'home.resultsN': ['%d 次', '%d {run|runs}'],
  'home.stop': ['停止', 'Stop'], 'home.stopping': ['正在停止', 'Stopping'],
  'home.answer': ['作答', 'Answer'], 'home.retry': ['重试', 'Retry'], 'home.resume': ['恢复派发', 'Resume dispatch'],
  'home.resumed': ['「%s」已恢复派发', 'Dispatch under %s goes on'], 'home.open': ['打开任务', 'Open the task'], 'home.collapse': ['收起', 'Collapse'],
  'home.other': ['其他…', 'Other…'], 'home.send': ['发送', 'Send'],
  'home.reply': ['回复，Enter 发送', 'A reply; Enter sends'], 'home.did': ['它刚做了', 'What it just did'],
  'home.toRun': ['回给 %s：它在这一轮里接着做', 'Goes back to %s: it carries on in this turn'],
  'home.toReply': ['作为回复发给 %s：同一个会话里接着做', 'A reply to %s: it carries on in the same session'],
  'home.checkPassed': ['check 通过：%s', 'Its check passed: %s'], 'home.changed': ['改动 · %d 个文件 · +%d −%d', 'Changes · %d {file|files} · +%d −%d'],
  'home.changedOne': ['改动 · 1 个文件 · +%d −%d', 'Changes · 1 file · +%d −%d'], 'home.openShort': ['打开', 'Open'],
  'home.openTask': ['打开任务 ›', 'Open the task ›'],
  'home.wait.permission': ['等你批准', 'To approve'], 'home.wait.answer': ['等你回答', 'To answer'], 'home.wait.attend': ['等你处理', 'To handle'], 'home.wait.accept': ['等你验收', 'To accept'],
  'home.wait.error': ['等你处理', 'To handle'],
  'home.nextLeft': ['处理完自动跳到下一条 · 还剩 %d 条 · 返回回到「等你」', 'Once handled the next one follows · %d more · Back returns to the list'],
  'home.nextNone': ['这是最后一条 · 处理完回到「等你」', 'The last one · once handled, the list comes back'],
  'home.allDone': ['都处理完了', 'All handled'], 'home.next': ['下一条', 'Next'],
  'home.goneTitle': ['已经不等你了', 'This no longer waits on you'], 'home.goneNote': ['可能别人已经处理，或者它已经结束。', 'Someone may have handled it, or it has ended.'],
  'home.done': ['完成', 'Done'], 'home.doneToast': ['「%s」已完成', '%s is done'], 'home.answered': ['已回复', 'Answered'],
  'home.confirmStop': ['停止这个运行？', 'Stop this run?'], 'home.confirmStopNote': ['「%s」在 %s 上的运行会被停下。', 'The run of %s on %s is stopped.'],
  'home.confirmRetry': ['重派这个任务？', 'Dispatch this task again?'], 'home.confirmRetryNote': ['「%s」会用 %s 在 %s 上再跑一次。', '%s runs again with %s on %s.'],
  'home.rework': ['改任务再派', 'Edit and dispatch'], 'home.reworkTitle': ['改「%s」再派', 'Edit “%s” and dispatch it'],
  'home.reworkBrief': ['任务书', 'Brief'], 'home.reworkGo': ['保存并再派', 'Save and dispatch'], 'home.reworkLoading': ['正在取任务书…', 'Fetching the brief…'],
  'home.reworkNote': ['先保存任务书，保存成功才再派一次，机器和 agent 与上次相同。', 'The brief is saved first; only then is the task dispatched again, on the same machine with the same agent.'],
  'home.reworked': ['「%s」已改好并再派', '“%s” edited and dispatched again'],
  'home.retryNote': ['补充一句（可选）', 'A word to add (optional)'], 'home.retryNoteHint': ['只加在这次运行的任务书后面，任务本身不改。', 'Added under this run\'s brief only; the task stays as it is.'],
  'home.perm': ['要执行 %s：%s', 'Wants to run %s: %s'], 'home.whyDetail': ['%s：%s', '%s: %s'],
  'home.slotBusy': ['等机器接手（%d/%d 在用）', 'Waits for its machine (%d/%d in use)'], 'home.g.n': ['%s %d', '%s %d'],
  'home.cancel': ['取消', 'Cancel'], 'home.waited': ['等了 %s', 'waited %s'],
  'home.end.exited': ['正常结束', 'Ended well'], 'home.end.checkFailed': ['check 没过', 'Its check failed'], 'home.end.exit': ['退出码 %d', 'Exit code %d'],
  'home.end.failed': ['出错', 'Failed'], 'home.end.stopped': ['已停止', 'Stopped'], 'home.end.canceled': ['已取消', 'Canceled'],
  'home.end.abandoned': ['已放弃', 'Abandoned'],
  'why.after': ['等前置任务', 'Waits for what comes first'], 'why.children': ['等子任务', 'Waits for its subtasks'],
  'why.slot': ['等机器接手', 'Waits for its machine'], 'why.drain': ['等机器恢复接新运行', 'Waits for its machine to take new runs again'],
  'why.paused': ['已暂停派发', 'Dispatch is paused'], 'why.dir': ['等同一目录的运行结束', 'Waits for the run in its directory'],
  'why.ready': ['即将派发', 'About to be dispatched'], 'why.completing': ['即将完成', 'About to be done'], 'why.accept': ['等验收', 'To be accepted'],
  'why.dispatch': ['等派发', 'To be dispatched'], 'why.after_canceled': ['前置任务已取消', 'A task it comes after was canceled'],
  'why.held': ['派不出去', 'Cannot be dispatched'], 'why.ended': ['运行结束，待确认完成', 'Its run ended; mark it done'],
  'why.asked': ['在问你', 'Asks you'], 'why.attend': ['等你处理', 'Needs you'], 'why.permission': ['等你批准', 'Waits for your approval'],
  'why.stalled': ['疑似卡住', 'May be stuck'],
  'why.unknown': ['结局不明', 'Its end is unknown'], 'why.failed': ['运行失败', 'Its run failed'], 'why.exited': ['非零退出', 'It exited with an error'],
  'why.stopped': ['已停止', 'Stopped'], 'why.canceled': ['已取消', 'Canceled'], 'why.abandoned': ['已放弃', 'Abandoned'],
  'why.access_revoked': ['派发人已无权使用这台机器', 'Its dispatcher lost access to the machine'],
  'why.source_changed': ['需求有变化', 'Its issue changed'], 'why.source_closed': ['issue 已在外面关闭', 'Its issue was closed outside tend'],
  'why.source_reopened': ['issue 在外面重新打开了', 'Its issue was reopened outside tend'],
  'why.advance': ['本阶段完成，即将进入下一阶段', 'Its stage is done; it moves on next'], 'why.rework': ['被退回，即将返工', 'Sent back; it goes back next'],
  'why.max_loops': ['退回次数到上限', 'Sent back as often as its workflow allows'], 'why.blocked': ['本阶段没有给出结论', 'Its stage reached no verdict'],
  'why.budget': ['用完了预算', 'Its budget is spent'], 'why.merge_conflict': ['合进父任务时冲突', 'Merging into its parent conflicted'],
  'why.stale': ['分支有了新提交，重新评审', 'Its branch moved on; judged again'], 'why.setup_failed': ['setup hook 失败', 'The setup hook failed'],
  'why.work': ['建不了工作区', 'Its worktree could not be made'], 'why.draft': ['拆解草稿等你确认', 'A plan waits for you'],
  'why.no_plan': ['拆解没有给出计划', 'Its planner handed in no plan'], 'why.other': ['需要你处理（%s）', 'Needs you (%s)'],
});

// apiText is what an /api failure says: the server's code in words, or the code as it is.
export const apiText = (w, e) => (w.has('api.' + e?.code) ? w.t('api.' + e.code) : w.f('app.failed', e?.code || String(e?.message || e)));

// why is what a reason code says; a code the table lacks is shown as it is.
export const why = (w, reason) => (w.has('why.' + reason) ? w.t('why.' + reason) : w.f('why.other', reason));
